name: OpenSSL


on: workflow_dispatch


jobs:
  windows-build:
    runs-on: windows-latests

    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: master
        submodules: recursive

    - name: Directory
      run: dir

    
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: master
        submodules: recursive

    - name: Install Perl
      run: sudo apt install -y perl

    - name: Build
      run: |
          mkdir -p install-dir/OpenSSL
          ./Configure --prefix=$(pwd)/install-dir/OpenSSL
          make install

    - name: Directory
      run: ls
