name: OpenSSL


on:
  push:
    branches: [dev]
  workflow_dispatch:


jobs:
  windows-build:
    runs-on: windows-latests

    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: master
        submodules: recursive

    - name: Build
      run: |
          perl Configure --prefix="$(pwd)/install-dir/OpenSSL"
          nmake install

    - name: Directory
      run: dir "$(pwd)/install-dir/OpenSSL"

    
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: master
        submodules: recursive
        
    - name: Build
      run: |
          mkdir -p install-dir/OpenSSL
          ./Configure --prefix=$(pwd)/install-dir/OpenSSL
          make install

    - name: Directory
      run: ls $(pwd)/install-dir/OpenSSL
