name: OpenSSL


on: workflow_dispatch


jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - name: Download latest OpenSSL
      uses: robinraju/release-downloader@v1.9
      with:
        repository: openssl/openssl
        latest: true
        extract: true
        zipBall: false
        tarBall: false
        
    - name: Prepare
      shell: bash
      run: |
          rm -f * || true
          cd */
          mv * ../
        
    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1

    - name: Setup NASM
      uses: ilammy/setup-nasm@v1
            
    - name: Build
      run: |
          mkdir ${{ github.workspace }}\install-dir\OpenSSL
          perl Configure no-shared no-docs no-legacy --prefix=${{ github.workspace }}\install-dir\OpenSSL
          nmake install

    - name: Rename
      run: |
          Rename-Item -Path .\install-dir\OpenSSL\lib\libssl.lib -NewName ssl.lib
          Rename-Item -Path .\install-dir\OpenSSL\lib\libcrypto.lib -NewName crypto.lib
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSSL_Windows
        path: ${{ github.workspace }}/install-dir/OpenSSL

    
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Download latest OpenSSL
      uses: robinraju/release-downloader@v1.9
      with:
        repository: openssl/openssl
        latest: true
        extract: true
        zipBall: false
        tarBall: false

    - name: Prepare
      run: |
          rm -f * || true
          cd */
          mv * ../
          
    - name: Build
      run: |
          mkdir -p install-dir/OpenSSL
          ./Configure no-shared no-docs no-legacy --prefix=${{ github.workspace }}/install-dir/OpenSSL
          make install
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSSL_Linux
        path: ${{ github.workspace }}/install-dir/OpenSSL

  android-build:
    runs-on: ubuntu-latest
    env:
      android-version: android-34
      android-platform: android-28
      sdk-install-name: platforms;android-34
      ndk-version: 27.0.12077973
      ndk-install-name: ndk;27.0.12077973

    steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt

    - name: Download latest OpenSSL
      uses: robinraju/release-downloader@v1.9
      with:
        repository: openssl/openssl
        latest: true
        extract: true
        zipBall: false
        tarBall: false

    - name: Prepare
      run: |
          rm -f * || true
          cd */
          mv * ../

    - name: Get Android SDK
      run: wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip

    - name: Setup Android SDK
      run: |
        unzip tools.zip
        rm -rf tools.zip
        shopt -s extglob
        cd cmdline-tools
        mkdir latest
        mv !(latest) latest/
        cd ..
        mkdir -p Android/Sdk
        mv cmdline-tools Android/Sdk
        cd Android/Sdk/cmdline-tools/latest/bin
        yes | ./sdkmanager --licenses
        ./sdkmanager "${{ env.sdk-install-name }}"
        ./sdkmanager --install "${{ env.ndk-install-name }}"
        ./sdkmanager --list | grep ndk

    - name: Build
      run: |
        export NDK_PATH=$(pwd)/Android/Sdk/ndk/${{ env.ndk-version }}
        export ANDROID_NDK_ROOT=${NDK_PATH}
        export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export CC=${NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-${{ env.android-version }}-clang
        export CXX=${NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-${{ env.android-version }}-clang++
        ./Configure no-shared no-docs no-legacy --prefix=${{ github.workspace }}/install-dir/OpenSSL android-arm64 -D__ANDROID_API__=28
        make install -j $(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSSL_Android
        path: ${{ github.workspace }}/install-dir/OpenSSL
