name: OpenSSL


on:
  push:
    branches: [dev]
  workflow_dispatch:


jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: master
        submodules: recursive

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0
            
    - name: Build
      run: |
          set CL=/MP
          perl Configure --prefix=${{ github.workspace }}/install-dir/OpenSSL
          nmake install

    - name: Directory
      run: dir ${{ github.workspace }}/install-dir/OpenSSL

    - name: Upload artifacts
      uses: actions/upload-artifact
      with:
        name: OpenSSL_Windows
        path: ${{ github.workspace }}/install-dir/OpenSSL

    
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: master
        submodules: recursive
        
    - name: Build
      run: |
          mkdir -p install-dir/OpenSSL
          ./Configure --prefix=${{ github.workspace }}/install-dir/OpenSSL
          make install -j $(nproc)

    - name: Directory
      run: ls ${{ github.workspace }}/install-dir/OpenSSL

    - name: Upload artifacts
      uses: actions/upload-artifact
      with:
        name: OpenSSL_Linux
        path: ${{ github.workspace }}/install-dir/OpenSSL
