name: OpenSSL


on: workflow_dispatch


env:
  OPEN_SSL_TAG: openssl-3.4.0
  android-api-version: 35


jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - name: Get OpenSSL
      uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: ${{ env.OPEN_SSL_TAG }}
        
    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1

    - name: Setup NASM
      uses: ilammy/setup-nasm@v1
            
    - name: Build
      run: |
          mkdir ${{ github.workspace }}\install-dir\OpenSSL
          perl Configure no-shared no-docs no-legacy --prefix=${{ github.workspace }}\install-dir\OpenSSL
          nmake install

    - name: Rename
      run: |
          Rename-Item -Path .\install-dir\OpenSSL\lib\libssl.lib -NewName ssl.lib
          Rename-Item -Path .\install-dir\OpenSSL\lib\libcrypto.lib -NewName crypto.lib
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSSL_Windows
        path: ${{ github.workspace }}/install-dir/OpenSSL

    
  linux-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get OpenSSL
      uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: ${{ env.OPEN_SSL_TAG }}
        
    - name: Build
      run: |
          mkdir -p install-dir/OpenSSL
          ./Configure no-shared no-docs no-legacy --prefix=${{ github.workspace }}/install-dir/OpenSSL
          make install
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSSL_Linux
        path: ${{ github.workspace }}/install-dir/OpenSSL


  android-build:
    runs-on: ubuntu-latest
    container:
      image: lazypanda07/ubuntu_cxx20:android
      
    steps:
    - name: Get OpenSSL
      uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: ${{ env.OPEN_SSL_TAG }}
        
    - name: Build
      run: |
        ./Configure no-shared no-docs no-legacy android-arm64 --prefix=/usr/local/OpenSSL -D__ANDROID_API__=${{ env.android-api-version }}
        make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSSL_Android
        path: /usr/local/OpenSSL
