name: OpenSSL


on:
  push:
    branches: [dev]
  workflow_dispatch:


jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: master
        submodules: recursive

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1

    - name: Setup NASM
      uses: ilammy/setup-nasm@v1
            
    - name: Build
      run: |
          mkdir ${{ github.workspace }}\install-dir\OpenSSL
          perl Configure no-shared no-docs no-legacy --prefix=${{ github.workspace }}\install-dir\OpenSSL
          nmake install
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSSL_Windows
        path: ${{ github.workspace }}/install-dir/OpenSSL

    
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: master
        submodules: recursive
        
    - name: Build
      run: |
          mkdir -p install-dir/OpenSSL
          ./Configure no-shared no-docs no-legacy --prefix=${{ github.workspace }}/install-dir/OpenSSL
          make install
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSSL_Linux
        path: ${{ github.workspace }}/install-dir/OpenSSL
